### ISSUE TITLE
Dex crash

### ISSUE THREAD

**Issue by stanch** [scala-android/sbt-android#21]
Hi,

I’m trying your plugin on the [_Macroid_](https://github.com/stanch/macroid) sample project: https://github.com/stanch/macroid-starter

Here’s my build.sbt: https://github.com/stanch/macroid-starter/blob/master/build.sbt

When `android:run` is performed for the first time, everything is fine. However, on subsequent invocations this is what happens:

```
[trace] Stack trace suppressed: run last android:dex for the full output.
[error] (android:dex) com.android.ide.common.internal.LoggedErrorException: Failed to run command:
[error]         C:\Progra~2\Android\android-sdk\build-tools\17.0.0\dx.bat -JXmx1024m --dex --incremental --no-strict --output C:\projects\macroid-starter\target\android-bin\classes.d
ex C:\Users\stanch\.ivy2\cache\com.android.support\support-v13\jars\support-v13-13.0.0.jar C:\Users\stanch\.ivy2\cache\com.scalarx\scalarx_2.10\jars\scalarx_2.10-0.1.jar C:\Users\sta
nch\.ivy2\cache\com.typesafe.akka\akka-actor_2.10\bundles\akka-actor_2.10-2.1.2.jar C:\Users\stanch\.ivy2\cache\io.dylemma\scala-frp_2.10\jars\scala-frp_2.10-1.0.jar C:\Users\stanch\
.ivy2\cache\org.scalaz\scalaz-core_2.10\bundles\scalaz-core_2.10-7.0.3.jar C:\projects\macroid-starter\target\android-bin\classes.jar C:\Users\stanch\.ivy2\cache\com.typesafe\config\
bundles\config-1.0.0.jar C:\Users\stanch\.ivy2\cache\com.android.support\support-v4\jars\support-v4-13.0.0.jar C:\projects\macroid-starter\target\scala-2.10\cache\default-42a471\glob
al\proguard_cache\proguard-cache-cdb4ee70ce1e1c206e16ebf6f9bc6f5db317c704.jar
[error] Error Code:
[error]         1
[error] Output:
[error]
[error]         UNEXPECTED TOP-LEVEL EXCEPTION:
[error]         java.lang.IllegalArgumentException: already added: Lorg/macroid/starter/MainActivity$$anon$1$$anonfun$1;
[error]                 at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:123)
[error]                 at com.android.dx.dex.file.DexFile.add(DexFile.java:163)
[error]                 at com.android.dx.command.dexer.Main.processClass(Main.java:490)
[error]                 at com.android.dx.command.dexer.Main.processFileBytes(Main.java:459)
[error]                 at com.android.dx.command.dexer.Main.access$400(Main.java:67)
[error]                 at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:398)
[error]                 at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
[error]                 at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:131)
[error]                 at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:109)
[error]                 at com.android.dx.command.dexer.Main.processOne(Main.java:422)
[error]                 at com.android.dx.command.dexer.Main.processAllFiles(Main.java:333)
[error]                 at com.android.dx.command.dexer.Main.run(Main.java:209)
[error]                 at com.android.dx.command.dexer.Main.main(Main.java:174)
[error]                 at com.android.dx.command.Main.main(Main.java:91)
[error]         1 error; aborting
[error] Total time: 17 s, completed 29.09.2013 4:14:12
```

Could you take a look?

**Comment by aguestuser** [comment]
Hi there. Similar issue. Also on Macroid. This is my [build file](https://github.com/the-learning-collective/whereat/blob/master/build.sbt). 

This is the sbt console output with the error message:

```shell
> android:run
[info] Processing resources
[info] [debug] cache hit, skipping proguard!
[info] Generating dex, incremental=true, multiDex=false

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lio/taig/communicator/package$$anon$1;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:732)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/ig;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:732)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
```
this is the full stack trace from running `last android:dex`

```shell
[info] Generating dex, incremental=true, multiDex=false
[debug] Dex inputs: List(/Users/aguestuser/code/tlc/whereat/target/aars/org.macroid-macroid_2.11-2.0.0-M4/org.macroid-macroid_2.11-2.0.0-M4.jar, /Users/aguestuser/code/tlc/whereat/target/aars/org.macroid-macroid-viewable_2.11-2.0.0-M4/org.macroid-macroid-viewable_2.11-2.0.0-M4.jar, /Users/aguestuser/code/tlc/whereat/target/aars/com.android.support-support-v4-22.1.1/com.android.support-support-v4-22.1.1.jar, /Users/aguestuser/code/tlc/whereat/target/aars/com.fortysevendeg-macroid-extras_2.11-0.1-SNAPSHOT/com.fortysevendeg-macroid-extras_2.11-0.1-SNAPSHOT.jar, /Users/aguestuser/code/tlc/whereat/target/aars/com.google.android.gms-play-services-6.5.87/com.google.android.gms-play-services-6.5.87.jar, /Users/aguestuser/code/tlc/whereat/target/aars/com.android.support-support-v4-22.1.1/libs/internal_impl-22.1.1.jar, /Users/aguestuser/.ivy2/cache/org.scala-lang.modules/scala-async_2.11/bundles/scala-async_2.11-0.9.2.jar, /Users/aguestuser/.ivy2/cache/org.brianmckenna/wartremover_2.11/jars/wartremover_2.11-0.10.jar, /Users/aguestuser/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar, /Users/aguestuser/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar, /Users/aguestuser/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/22.1.1/support-annotations-22.1.1.jar, /Users/aguestuser/.ivy2/cache/io.taig/communicator_2.11/jars/communicator_2.11-2.0.1.jar, /Users/aguestuser/.ivy2/cache/com.squareup.okhttp/okhttp/jars/okhttp-2.2.0.jar, /Users/aguestuser/.ivy2/cache/com.squareup.okio/okio/jars/okio-1.2.0.jar, /Users/aguestuser/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.3.4.jar, /Users/aguestuser/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.3.4.jar, /Users/aguestuser/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar, /Users/aguestuser/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar, /Users/aguestuser/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.3.4.jar, /Users/aguestuser/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.3.4.jar, /Users/aguestuser/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.3.jar, /Users/aguestuser/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.6.jar, /Users/aguestuser/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.2.jar, /Users/aguestuser/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.2.jar, /Users/aguestuser/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.2.jar, /Users/aguestuser/code/tlc/whereat/target/streams/android/proguardInputs/$global/streams/proguard_cache/proguard-cache-895a6f2501c1f77c0f71d80fe741b4f1b9c1de5c.jar, /Users/aguestuser/code/tlc/whereat/target/android-bin/classes.jar)
com.android.ide.common.process.ProcessException: error code: 1
        at android.Plugin$$anonfun$allPluginSettings$99$$anon$2$$anon$3.assertNormalExitValue(rules.scala:513)
        at android.Plugin$$anonfun$allPluginSettings$99$$anon$2$$anon$3.assertNormalExitValue(rules.scala:511)
        at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1194)
        at android.Tasks$$anonfun$73.apply(tasks.scala:1160)
        at android.Tasks$$anonfun$73.apply(tasks.scala:1137)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:35)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
I'm having some trouble fishing out the correct lines from logcat, but would happily provide those if giving some guidance on how to do so. Thanks!

**Comment by pfn** [comment]
the syntax of ProguardCache is:

ProguardCache("package-name(s)"...) % "organization" % "artifact"

**Comment by aguestuser** [comment]
thank you! fixed the syntax. still get the same error message. suggestions? more helpful error output I could produce?

**Comment by aguestuser** [comment]
Sorry! Realized I still had the syntax wrong. Now it's right, and it works! Thanks for your time, your fantastically useful plugin, and your many helpful pointers! :)
