### ISSUE TITLE
java.lang.ClassNotFoundException: com.android.sdklib.SdkManager

### ISSUE THREAD

**Issue by carlos-sancho-ramirez** [scala-android/sbt-android#257]
Hi there,

I am currently working in a personal project that uses this plugin. This project is public in github. Here there is a [link](https://github.com/carlos-sancho-ramirez/android-scala-langbook/tree/b3c710c83d417820808cb1fee07b43ba8adcc775) to the project in case the issue want to be reproduced.

I tried to update to the newest version 1.6.0 as suggested in the README file but it looks that it is not able to find some of the classes in the jars within the android sdk folder. But they are actually there, and the ANDROID_HOME environment variable is set as expected. What surprises me the most is that it works perfectly if I include
    addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.6.0")
in the project/android.sbt file, but not if I changed to the suggested way, which is
    addSbtPlugin("org.scala-android" % "sbt-android" % "1.6.0")

I tried removing the ivy cache, just in case, but it did not fix it. Whenever I try to run the project with
    $ sbt clean android:run
I get the following output:
[info] Loading global plugins from /home/charlie/.sbt/0.13/plugins
[info] Loading project definition from /home/charlie/repos/android-scala-langbook/project
java.lang.NoClassDefFoundError: com/android/sdklib/SdkManager
	at android.Keys$Internal$.<init>(keys.scala:297)
	at android.Keys$Internal$.<clinit>(keys.scala)
	at android.Tasks$.<init>(tasks.scala:123)
	at android.Tasks$.<clinit>(tasks.scala)
	at android.AutoBuild$class.projects(rules.scala:1001)
	at Build$.projects(build.scala:1)
	at sbt.Build$class.projectDefinitions(Build.scala:12)
	at Build$.projectDefinitions(build.scala:1)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: com.android.sdklib.SdkManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at android.Keys$Internal$.<init>(keys.scala:297)
	at android.Keys$Internal$.<clinit>(keys.scala)
	at android.Tasks$.<init>(tasks.scala:123)
	at android.Tasks$.<clinit>(tasks.scala)
	at android.AutoBuild$class.projects(rules.scala:1001)
	at Build$.projects(build.scala:1)
	at sbt.Build$class.projectDefinitions(Build.scala:12)
	at Build$.projectDefinitions(build.scala:1)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: com/android/sdklib/SdkManager

May it be an error in the dependencies for the version in scala-android? I do not know how to proceed, so any help would be appreciated.

Thanks!

**Comment by pfn** [comment]
You have the old android-sdk-plugin setup globally in ~/.sbt/0.13/plugins

Update it.

**Comment by pfn** [comment]
Reopen if the global/local plugin isn't the issue

**Comment by carlos-sancho-ramirez** [comment]
I just tested it. You are completely right. I had a file in ~/.sbt/0.13/plugins/android.sbt with content
    addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.5.14")
that for sure I added time ago and I did not remember. Just removing that file all works perfectly again.

Many thanks for your help and for your great work with this plugin!
