### ISSUE TITLE
Race condition is back?

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#277]
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: ...

I'm using 1.6.6 and it seems this old exception is back. It occurs ~50% of the times when launching apps. And when that happens I have to do a clean and rebuild which is annoying.

**Comment by pfn** [comment]
Include full log.

**Comment by Mygod** [comment]
Here's another error.

```
07-12 00:30:26.839 14018-14018/tk.mygod.portal.helper.nju E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: tk.mygod.portal.helper.nju, PID: 14018
                                                                            java.lang.IncompatibleClassChangeError: Couldn't find scala.reflect.ScalaSignature.bytes
                                                                                at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
                                                                                at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
                                                                                at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
                                                                                at libcore.reflect.AnnotationAccess.getAnnotations(AnnotationAccess.java:111)
                                                                                at java.lang.Class.getAnnotations(Class.java:369)
                                                                                at com.j256.ormlite.misc.JavaxPersistence.getEntityName(JavaxPersistence.java:213)
                                                                                at com.j256.ormlite.table.DatabaseTableConfig.extractTableName(DatabaseTableConfig.java:161)
                                                                                at com.j256.ormlite.android.DatabaseTableConfigUtil.fromClass(DatabaseTableConfigUtil.java:46)
                                                                                at com.j256.ormlite.db.SqliteAndroidDatabaseType.extractDatabaseTableConfig(SqliteAndroidDatabaseType.java:76)
                                                                                at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:67)
                                                                                at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.getDao(OrmLiteSqliteOpenHelper.java:279)
                                                                                at tk.mygod.portal.helper.nju.database.DatabaseManager$.noticeDao$lzycompute(DatabaseManager.scala:16)
                                                                                at tk.mygod.portal.helper.nju.database.DatabaseManager$.noticeDao(DatabaseManager.scala:16)
                                                                                at tk.mygod.portal.helper.nju.NoticeManager$.fetchAllNotices(NoticeManager.scala:47)
                                                                                at tk.mygod.portal.helper.nju.NoticeActivity.onCreate(NoticeActivity.scala:77)
                                                                                at android.app.Activity.performCreate(Activity.java:6237)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```

**Comment by Mygod** [comment]
I'll try to get the full error log for that one if it comes back.

**Comment by pfn** [comment]
There is no race condition... what you're posting is unrelated. as for
java.lang.IncompatibleClassChangeError: Couldn't find
scala.reflect.ScalaSignature.bytes; you probably need to add the
appropriate proguard rule for that.

**Comment by Mygod** [comment]
If that's the case, rebuilding wouldn't have helped.

**Comment by pfn** [comment]
wrong

**Comment by pfn** [comment]
please see #200

**Comment by Mygod** [comment]
Turning off `proguardCache` seemed to work. Thanks.

**Comment by pfn** [comment]
Not the proper solution to use though...

**Comment by Mygod** [comment]
Well I'm not going to maintain a list of all the packages that my code and the dependencies used. :/

**Comment by pfn** [comment]
There's no list to maintain

**Comment by Mygod** [comment]
Hmm could you be a little more specific of what the proper fix is then, please?

**Comment by pfn** [comment]
The proper fix is to add libraries to cache if they're missing and vice
versa

**Comment by Mygod** [comment]
Here's the other weird bug.
```
07-13 13:41:26.499 7066-7066/tk.mygod.portal.helper.nju D/AndroidRuntime: Shutting down VM
07-13 13:41:26.500 7066-7066/tk.mygod.portal.helper.nju E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: tk.mygod.portal.helper.nju, PID: 7066
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.mygod.portal.helper.nju/tk.mygod.portal.helper.nju.MainActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
                                                                           Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class x
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                              at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                              at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:738)
                                                                              at android.view.LayoutInflater.inflate(<Xposed>)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:419)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                              at tk.mygod.portal.helper.nju.MainActivity.onCreate(MainActivity.scala:29)
                                                                              at android.app.Activity.performCreate(Activity.java:6237)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class x
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                              at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                              at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:738) 
                                                                              at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:419) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at tk.mygod.portal.helper.nju.MainActivity.onCreate(MainActivity.scala:29) 
                                                                              at android.app.Activity.performCreate(Activity.java:6237) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134) 
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/tk.mygod.portal.helper.nju-2/base.apk"],nativeLibraryDirectories=[/data/app/tk.mygod.portal.helper.nju-2/lib/arm, /vendor/lib, /system/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                              at android.view.LayoutInflater.onCreateView(LayoutInflater.java:677)
                                                                              at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                                                                              at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                              at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                              at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:738) 
                                                                              at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:419) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at tk.mygod.portal.helper.nju.MainActivity.onCreate(MainActivity.scala:29) 
                                                                              at android.app.Activity.performCreate(Activity.java:6237) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134) 
                                                                          	Suppressed: java.lang.ClassNotFoundException: android.view.x
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                              		... 31 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-13 13:41:26.507 2282-7258/system_process W/ActivityManager:   Force finishing activity tk.mygod.portal.helper.nju/.MainActivity
07-13 13:41:27.025 2282-2330/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{a04583b u0 tk.mygod.portal.helper.nju/.MainActivity t11277 f}
```

Building with `android:run` again without cleaning worked.

**Comment by pfn** [comment]
Your layout xml is malformes

**Comment by Mygod** [comment]
But that wouldn't explain why rebuilding the code makes this error goes away.

**Comment by pfn** [comment]
Lack of detail makes it impossible to explain. Your layout xml is malformed
until details show otherwise.
