### ISSUE TITLE
java.util.NoSuchElementException (1.6.7)

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#279]
```
[info] Loading project definition from /home/mygod/Products/GitHub/nju-portal-login-android/project
[info] Set current project to nju-portal-login-android (in build file:/home/mygod/Products/GitHub/nju-portal-login-android/)
java.util.NoSuchElementException: key not found: toolbar_light_dark
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:58)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:58)
        at android.Resources$$anonfun$generateViewHolders$1$$anonfun$android$Resources$$anonfun$$processViews$1$1.apply(resources.scala:747)
        at android.Resources$$anonfun$generateViewHolders$1$$anonfun$android$Resources$$anonfun$$processViews$1$1.apply(resources.scala:737)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at android.Resources$$anonfun$generateViewHolders$1.android$Resources$$anonfun$$processViews$1(resources.scala:737)
        at android.Resources$$anonfun$generateViewHolders$1$$anonfun$49.apply(resources.scala:767)
        at android.Resources$$anonfun$generateViewHolders$1$$anonfun$49.apply(resources.scala:764)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at android.Resources$$anonfun$generateViewHolders$1.apply(resources.scala:764)
        at android.Resources$$anonfun$generateViewHolders$1.apply(resources.scala:701)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
        at android.Resources$.generateViewHolders(resources.scala:792)
        at android.Tasks$$anonfun$27.apply(tasks.scala:309)
        at android.Tasks$$anonfun$27.apply(tasks.scala:308)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (android:viewholdersGenerator) java.util.NoSuchElementException: key not found: toolbar_light_dark
[error] Total time: 1 s, completed Jul 12, 2016 7:23:42 PM
```

I have this in my `activity_main.xml`:

    <include layout="@layout/toolbar_light_dark"/>

Where `toolbar_light_dark.xml` is in another library.

**Comment by pfn** [comment]
Set `typedResourcesAar := true`

**Comment by Mygod** [comment]
Oh ok.

**Comment by Mygod** [comment]
Btw could you fix this error since the library may not be able to use typed resources?

**Comment by pfn** [comment]
The error will remain, but the message will change. You can disable typed
view holders by setting `typedViewHolders := false`
