### ISSUE TITLE
java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by relrod** [scala-android/sbt-android#283]
I'm trying to set up the plugin (globally), but hitting this exception. Below is output of what I did and what happened:

```
ricky@t520 100% /tmp/foo$ sbt -sbt-create 'gen-android foo.bar Baz'
Downloading sbt launcher for 0.13.12:
  From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.12/sbt-launch.jar
    To  /home/ricky/.sbt/launchers/0.13.12/sbt-launch.jar
Getting org.scala-sbt sbt 0.13.12 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.12/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.12!sbt.jar (983ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar ...
	[SUCCESSFUL ] org.scala-sbt#main;0.13.12!main.jar (5961ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.12/jars/compiler-interface.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.12!compiler-interface.jar (1468ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.12/jars/actions.jar ...
	[SUCCESSFUL ] org.scala-sbt#actions;0.13.12!actions.jar (1860ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.12/jars/main-settings.jar ...
	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.12!main-settings.jar (2169ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.12/jars/interface.jar ...
	[SUCCESSFUL ] org.scala-sbt#interface;0.13.12!interface.jar (960ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.12/jars/io.jar ...
	[SUCCESSFUL ] org.scala-sbt#io;0.13.12!io.jar (1468ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.12/jars/ivy.jar ...
	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.12!ivy.jar (4687ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.12/jars/logging.jar ...
	[SUCCESSFUL ] org.scala-sbt#logging;0.13.12!logging.jar (1034ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.12/jars/logic.jar ...
	[SUCCESSFUL ] org.scala-sbt#logic;0.13.12!logic.jar (942ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.12/jars/process.jar ...
	[SUCCESSFUL ] org.scala-sbt#process;0.13.12!process.jar (1048ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.12/jars/run.jar ...
	[SUCCESSFUL ] org.scala-sbt#run;0.13.12!run.jar (1053ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.12/jars/command.jar ...
	[SUCCESSFUL ] org.scala-sbt#command;0.13.12!command.jar (1548ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.12/jars/classpath.jar ...
	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.12!classpath.jar (1086ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.12/jars/completion.jar ...
	[SUCCESSFUL ] org.scala-sbt#completion;0.13.12!completion.jar (1694ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.12/jars/api.jar ...
	[SUCCESSFUL ] org.scala-sbt#api;0.13.12!api.jar (1541ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.12/jars/compiler-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.12!compiler-integration.jar (1072ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.12/jars/compiler-ivy-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.12!compiler-ivy-integration.jar (863ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.12/jars/relation.jar ...
	[SUCCESSFUL ] org.scala-sbt#relation;0.13.12!relation.jar (863ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.12/jars/task-system.jar ...
	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.12!task-system.jar (1035ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.12/jars/tasks.jar ...
	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.12!tasks.jar (1080ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.12/jars/tracking.jar ...
	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.12!tracking.jar (1095ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.12/jars/testing.jar ...
	[SUCCESSFUL ] org.scala-sbt#testing;0.13.12!testing.jar (1024ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.12/jars/control.jar ...
	[SUCCESSFUL ] org.scala-sbt#control;0.13.12!control.jar (843ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.12/jars/collections.jar ...
	[SUCCESSFUL ] org.scala-sbt#collections;0.13.12!collections.jar (4341ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.12/jars/classfile.jar ...
	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.12!classfile.jar (1051ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.12/jars/incremental-compiler.jar ...
	[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.12!incremental-compiler.jar (4386ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar ...
	[SUCCESSFUL ] org.scala-sbt#compile;0.13.12!compile.jar (3002ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.12/jars/persist.jar ...
	[SUCCESSFUL ] org.scala-sbt#persist;0.13.12!persist.jar (1129ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.12/jars/cross.jar ...
	[SUCCESSFUL ] org.scala-sbt#cross;0.13.12!cross.jar (868ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.12/jars/cache.jar ...
	[SUCCESSFUL ] org.scala-sbt#cache;0.13.12!cache.jar (1000ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.12/jars/test-agent.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.12!test-agent.jar (886ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.12/jars/apply-macro.jar ...
	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.12!apply-macro.jar (948ms)
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	49 artifacts copied, 0 already retrieved (17462kB/145ms)
Getting Scala 2.10.6 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (24494kB/191ms)
[info] Loading global plugins from /home/ricky/.sbt/0.13/plugins
[info] Updating {file:/home/ricky/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to foo (in build file:/tmp/foo/)
[info] Creating project: Baz
[info] Creating SBT project files
ricky@t520 100% /tmp/foo$ sbt compile
[info] Loading global plugins from /home/ricky/.sbt/0.13/plugins
[info] Loading project definition from /tmp/foo/project
[info] Updating {file:/tmp/foo/project/}foo-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Observed package id 'system-images;android-19;default;armeabi-v7a' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/armeabi-v7a' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/armeabi-v7a')
[warn] Observed package id 'system-images;android-19;default;x86' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/x86' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/x86')
[warn] Observed package id 'system-images;android-19;default;armeabi-v7a' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/armeabi-v7a' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/armeabi-v7a')
[warn] Observed package id 'system-images;android-19;default;x86' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/x86' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/x86')
[info] Set current project to foo (in build file:/tmp/foo/)
[warn] Observed package id 'system-images;android-19;default;armeabi-v7a' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/armeabi-v7a' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/armeabi-v7a')
[warn] Observed package id 'system-images;android-19;default;x86' in inconsistent location '/home/ricky/devel/android-sdk-linux/system-images/android-19/x86' (Expected '/home/ricky/devel/android-sdk-linux/system-images/android-19/default/x86')
[info] Updating {file:/tmp/foo/}foo...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:runner:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:exposed-instrumentation-api-publish:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-core:2.2.2:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test:rules:0.5:androidTest
[warn] androidTest: test-only aar will not have resources merged com.android.support.test.espresso:espresso-idling-resource:2.2.2:androidTest
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:337)
	at scala.collection.immutable.Nil$.head(List.scala:334)
	at android.Dependencies$AarLibrary.moduleID$lzycompute(dependencies.scala:89)
	at android.Dependencies$AarLibrary.moduleID(dependencies.scala:87)
	at android.Dependencies$LibEquals.hashCode(dependencies.scala:136)
	at scala.collection.mutable.FlatHashTable$HashUtils$class.elemHashCode(FlatHashTable.scala:391)
	at scala.collection.mutable.HashSet.elemHashCode(HashSet.scala:41)
	at scala.collection.mutable.FlatHashTable$class.findEntryImpl(FlatHashTable.scala:123)
	at scala.collection.mutable.FlatHashTable$class.containsEntry(FlatHashTable.scala:119)
	at scala.collection.mutable.HashSet.containsEntry(HashSet.scala:41)
	at scala.collection.mutable.HashSet.contains(HashSet.scala:58)
	at scala.collection.GenSetLike$class.apply(GenSetLike.scala:43)
	at scala.collection.mutable.AbstractSet.apply(Set.scala:45)
	at scala.collection.SeqLike$$anonfun$distinct$1.apply(SeqLike.scala:494)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.SeqLike$class.distinct(SeqLike.scala:493)
	at scala.collection.AbstractSeq.distinct(Seq.scala:40)
	at android.Dependencies$LibrarySeqOps.distinctLibs(dependencies.scala:146)
	at android.Resources$.collectdeps(resources.scala:323)
	at android.Resources$.doCollectResources(resources.scala:68)
	at android.Tasks$$anonfun$40$$anonfun$apply$45.apply(tasks.scala:489)
	at android.Tasks$$anonfun$40$$anonfun$apply$45.apply(tasks.scala:488)
	at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:847)
	at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:845)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at android.Tasks$.withCachedRes(tasks.scala:848)
	at android.Tasks$$anonfun$40.apply(tasks.scala:488)
	at android.Tasks$$anonfun$40.apply(tasks.scala:476)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.android.builder.core.AndroidBuilder.mergeManifests(AndroidBuilder.java:693)
	at android.Tasks$$anonfun$58.apply(tasks.scala:761)
	at android.Tasks$$anonfun$58.apply(tasks.scala:746)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.android.manifmerger.ManifestMerger2.loadLibraries(ManifestMerger2.java:586)
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:126)
	at com.android.manifmerger.ManifestMerger2.access$1100(ManifestMerger2.java:58)
	at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1163)
	at com.android.builder.core.AndroidBuilder.mergeManifests(AndroidBuilder.java:654)
	at android.Tasks$$anonfun$58.apply(tasks.scala:761)
	at android.Tasks$$anonfun$58.apply(tasks.scala:746)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:181)
	at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:139)
	at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:101)
	at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:110)
	at com.android.manifmerger.XmlLoader.load(XmlLoader.java:63)
	at com.android.manifmerger.ManifestMerger2.loadLibraries(ManifestMerger2.java:578)
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:126)
	at com.android.manifmerger.ManifestMerger2.access$1100(ManifestMerger2.java:58)
	at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1163)
	at com.android.builder.core.AndroidBuilder.mergeManifests(AndroidBuilder.java:654)
	at android.Tasks$$anonfun$58.apply(tasks.scala:761)
	at android.Tasks$$anonfun$58.apply(tasks.scala:746)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:337)
	at scala.collection.immutable.Nil$.head(List.scala:334)
	at android.Dependencies$AarLibrary.moduleID$lzycompute(dependencies.scala:89)
	at android.Dependencies$AarLibrary.moduleID(dependencies.scala:87)
	at android.Tasks$$anonfun$100$$anonfun$apply$111.apply(tasks.scala:1469)
	at android.Tasks$$anonfun$100$$anonfun$apply$111.apply(tasks.scala:1468)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at android.Tasks$$anonfun$100.apply(tasks.scala:1468)
	at android.Tasks$$anonfun$100.apply(tasks.scala:1454)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (android:collectResources) java.util.NoSuchElementException: head of empty list
[error] (android:processManifest) com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[error] (compile:unmanagedJars) java.util.NoSuchElementException: head of empty list
[error] Total time: 1 s, completed Aug 20, 2016 6:47:09 AM
```

... It's worth noting that my laptop hardlocked during one of my first attempts, so something might have gotten into a weird state somewhere, but I've tried clearing everything I can think of (including blowing `~/.sbt` and every other possibly-related dot-directory in my home directory that I could think of and starting from scratch) and I can't seem to find the culprit.

**Comment by pfn** [comment]
rm -rf ~/.android/sbt/exploded-aars

**Comment by relrod** [comment]
Yep, that was it! Thank you!
