### ISSUE TITLE
Trouble starting project

### ISSUE THREAD

**Issue by drewhk** [scala-android/sbt-android#300]
I tried setting up a new, test project from scratch, but I run into problems quickly. First of all, the plugin does not seem to find my Android SDK, although the env variable is set:

```
C:\REDACTED\android-test>set ANDROID_HOME
ANDROID_HOME=E:/lib/android_r25.2.3/
```

(btw, I tried both forward and backward slashes, and slash or no-slash at the end. All the same result)

Now, this would not be tragic, as it seems to start downloading the tools. However, it eventually runs into this problem:

```
[warn] latest build-tools not found, searching for package...
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Build-Tools 25.0.2' ...
Downloading /android/repository/build-tools_r25.0.2-windows.zip            100%
Unzipping... / android-7.1.1/apksigner.bat                                 100%
Fetch remote repository...                                                 100%
java.lang.RuntimeException: Setting value cannot be null: {file:/C:/Users/REDACTED/android-test/}android-test/android:buildTools

        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/C:/Users/Varga/workspace/android-test/}android-test/android:buildTools
[error] Use 'last' for the full log.
```

Unfortunately, the error is not informative at all, and I have trouble even finding out where it is actually originating from (due to some async magic, I assume, which eradicates the important part of the stacktrace).

**Comment by pfn** [comment]
You set ANDROID_HOME incorrectly, it must point to the base folder.

Alternatively, do not set it at all

**Comment by drewhk** [comment]
What do you mean by base folder? This is NOT the platforms folder, this is the top level directory. I just renamed it to reflect the release version (if you unpack the ZIP, this folder is called `tools`).

**Comment by drewhk** [comment]
```
 Directory of E:\lib\android_r25.2.3

2017. 02. 15.  16:59    <DIR>          .
2017. 02. 15.  16:59    <DIR>          ..
2017. 02. 15.  16:59                16 .knownPackages
2016. 11. 11.  17:37             3 724 android.bat
2017. 02. 15.  16:18    <DIR>          ant
2017. 02. 15.  16:18    <DIR>          apps
2017. 02. 15.  16:18    <DIR>          bin
2017. 02. 15.  16:59    <DIR>          build-tools
2016. 11. 11.  17:37             2 442 ddms.bat
2016. 11. 11.  17:37             1 451 draw9patch.bat
2016. 11. 11.  17:37         9 482 752 emulator-arm.exe
2016. 11. 11.  17:37           595 456 emulator-check.exe
2016. 11. 11.  17:37         7 043 072 emulator-crash-service.exe
2016. 11. 11.  17:37         9 577 984 emulator-mips.exe
2016. 11. 11.  17:37         9 698 816 emulator-x86.exe
2016. 11. 11.  17:37           760 832 emulator.exe
2016. 11. 11.  17:37         7 167 488 emulator64-crash-service.exe
2016. 11. 11.  17:37             2 535 hierarchyviewer.bat
2016. 11. 11.  17:37             1 650 jobb.bat
2017. 02. 15.  16:18    <DIR>          lib
2017. 02. 15.  16:18    <DIR>          lib64
2017. 02. 15.  16:45    <DIR>          licenses
2016. 11. 11.  17:37             1 926 lint.bat
2016. 11. 11.  17:37           230 362 mksdcard.exe
2016. 11. 11.  17:37             1 108 monitor.bat
2016. 11. 11.  17:37             1 948 monkeyrunner.bat
2016. 11. 11.  17:37           839 230 NOTICE.txt
2017. 02. 15.  16:59    <DIR>          platform-tools
2017. 02. 15.  16:47    <DIR>          platforms
2017. 02. 15.  16:18    <DIR>          proguard
2017. 02. 15.  16:18    <DIR>          qemu
2016. 11. 11.  17:42                70 source.properties
2017. 02. 15.  16:18    <DIR>          support
2017. 02. 15.  16:18    <DIR>          templates
2017. 02. 15.  16:59    <DIR>          tools
2016. 11. 11.  17:37             2 061 traceview.bat
2016. 11. 11.  17:37             2 075 uiautomatorviewer.bat
              21 File(s)     45 416 998 bytes
              16 Dir(s)  105 020 776 448 bytes free
```

**Comment by pfn** [comment]
That is incorrect. The tools/ folder must exist inside of ANDROID_HOME

**Comment by drewhk** [comment]
I also tried now cleaning the ANDROID_HOME variable, and still get the same:

```
C:\Users\REDACTED\android-test>set ANDROID_HOME
Environment variable ANDROID_HOME not defined

C:\Users\REDACTED\android-test>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\REDACTED\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\REDACTED\workspace\android-test\project
[warn] android sdk tools not found, searching for package...
[warn] File C:\Users\REDACTED\.android\repositories.cfg could not be loaded.   25%
Computing updates...                                                       100%
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Tools 25.2.5' ...
Downloading /android/repository/tools_r25.2.5-windows.zip                  100%
Unzipping... / tools/android.bat                                           100%
Fetch remote repository...                                                 100%
[warn] android platform-tools not found, searching for package...
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Platform-Tools' ...
Downloading /android/repository/platform-tools_r25.0.3-windows.zip         100%
Unzipping... / platform-tools/systrace/NOTICE                              100%
Fetch remote repository...                                                 100%
[warn] latest build-tools not found, searching for package...
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Build-Tools 25.0.2' ...
Downloading /android/repository/build-tools_r25.0.2-windows.zip            100%
Unzipping... / android-7.1.1/apksigner.bat                                 100%
Fetch remote repository...                                                 100%
java.lang.RuntimeException: Setting value cannot be null: {file:/C:/Users/Varga/workspace/android-test/}android-test/android:buildTools

        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by drewhk** [comment]
bq. That is incorrect. The tools/ folder must exist inside of ANDROID_HOME

Do you read what I post?

```
2017. 02. 15.  16:59    <DIR>          tools
```

**Comment by pfn** [comment]
None of ddms.bat etc must exist in ANDROID_HOME

**Comment by drewhk** [comment]
I am not sure now where that variable should point then. But OK, I unset the variable, and it still fails with the exception I provided above.

**Comment by pfn** [comment]
Start a new shell with the variable unset

**Comment by drewhk** [comment]
That is what I pasted you in comment https://github.com/scala-android/sbt-android/issues/300#issuecomment-280056023

**Comment by pfn** [comment]
The only reason this happens is if ANDROID_HOME is corrupt `rd /s
%ANDROID_HOME%`

**Comment by drewhk** [comment]
ANDROID_HOME is not set. It still gives the same exception. What would you accept as proof that my ANDROID_HOME is not set? I completely removed the variable, restarted the system, **again** confirmed, that it is unset:

```
C:\Users\REDACTED\android-test>set ANDROID_HOME
Environment variable ANDROID_HOME not defined
```

and the output is exactly the same from SBT:

```
[warn] android sdk tools not found, searching for package...
[warn] File C:\Users\Varga\.android\repositories.cfg could not be loaded.   25%
Computing updates...                                                       100%
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Tools 25.2.5' ...
Downloading /android/repository/tools_r25.2.5-windows.zip                  100%
Unzipping... / tools/android.bat                                           100%
Fetch remote repository...                                                 100%
[warn] android platform-tools not found, searching for package...
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Platform-Tools' ...
Downloading /android/repository/platform-tools_r25.0.3-windows.zip         100%
Unzipping... / platform-tools/systrace/NOTICE                              100%
Fetch remote repository...                                                 100%
[warn] latest build-tools not found, searching for package...
By continuing to use sbt-android, you accept the terms of 'android-sdk-license'
You may review the terms by running 'android-license android-sdk-license'
[info] Installing package 'Android SDK Build-Tools 25.0.2' ...
Downloading /android/repository/build-tools_r25.0.2-windows.zip            100%
Unzipping... / android-7.1.1/apksigner.bat                                 100%
Fetch remote repository...                                                 100%
java.lang.RuntimeException: Setting value cannot be null: {file:/C:/Users/Varga/workspace/android-test/}android-test/android:buildTools

        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/C:/Users/Varga/workspace/android-test/}android-test/android:buildTools
```

**Comment by pfn** [comment]
Restarting sbt should work around this
